<TS language="hi" version="2.1">
<context>
    <name>AboutDialog</name>
    </context>
<context>
    <name>CommandLineEdit</name>
    </context>
<context>
    <name>CreditsDialog</name>
    </context>
<context>
    <name>FolderSelectionWidget</name>
    </context>
<context>
    <name>GlobalPreferencesDialog</name>
    </context>
<context>
    <name>ImageTaskExportWidget</name>
    </context>
<context>
    <name>ImageTaskImageWidget</name>
    </context>
<context>
    <name>ImageTaskRunnerWidget</name>
    </context>
<context>
    <name>ImageTaskScriptPanel</name>
    </context>
<context>
    <name>ImageTaskStatsWidget</name>
    </context>
<context>
    <name>ImageTaskWindow</name>
    </context>
<context>
    <name>LanguageSelectWidget</name>
    </context>
<context>
    <name>LaunchWindow</name>
    </context>
<context>
    <name>LicenseDialog</name>
    </context>
<context>
    <name>OpenUrlDialog</name>
    </context>
<context>
    <name>QWidget</name>
    </context>
<context>
    <name>RunScriptDialog</name>
    </context>
<context>
    <name>Script evaluation error dialog title</name>
    </context>
<context>
    <name>Script evaluation error message</name>
    </context>
<context>
    <name>Script evaluation unknown error</name>
    </context>
<context>
    <name>ScriptEditorWidget</name>
    </context>
<context>
    <name>WelcomeDialog</name>
    </context>
<context>
    <name>geometrize::dialog::AboutDialog</name>
    </context>
<context>
    <name>geometrize::dialog::CreditsDialog</name>
    </context>
<context>
    <name>geometrize::dialog::ImageTaskExportWidget</name>
    </context>
<context>
    <name>geometrize::dialog::ImageTaskStatsWidget</name>
    </context>
<context>
    <name>geometrize::dialog::ImageTaskWindow</name>
    </context>
<context>
    <name>geometrize::dialog::LaunchWindow</name>
    </context>
<context>
    <name>geometrize::dialog::RecentItemWidget</name>
    </context>
<context>
    <name>geometrize::dialog::ScriptConsole</name>
    </context>
<context>
    <name>geometrize::dialog::TemplateButton</name>
    </context>
<context>
    <name>geometrize::dialog::WelcomeDialog</name>
    </context>
<context>
    <name>geometrize::strings::Strings</name>
    </context>
</TS>